### ISSUE TITLE
add error handling

### ISSUE THREAD

**Issue by thewildofficial** [DeadPackets/pwnbox#1]
pip installs perfectly with no issues.
on running `pwnbox up`,the following error is thrown
```File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pwnbox", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pwnbox/__main__.py", line 127, in main
    pwnbox_container = client.containers.get(config['CONTAINER']['NAME'])
AttributeError: 'function' object has no attribute 'get'
```

this appears to be a _docker_ error,but some handling would be really useful for the scriptkiddie :)

**Comment by DeadPackets** [comment]
Can you re-open this issue in [pwnbox-cli](https://github.com/deadpackets/pwnbox-cli)?

Appreciated.
