### ISSUE TITLE
Remote Desktop Protocol

### ISSUE THREAD

**Issue by HiddevH** [DeadPackets/pwnbox#10]
Hello!

One of the tutorial HTB machines required RDP. Since this is GUI oriented, the Pwnbox container was not meeting the requirements.

I've never tried running GUI applications from a Docker container before, but it seems possible:
`https://www.cloudsavvyit.com/10520/how-to-run-gui-applications-in-a-docker-container/` 

Might be cool at some point to have this, although I don't know how feasible. What do you think?

**Comment by DeadPackets** [comment]
Pwnbox should be able to run GUI applications by default. You're running on an M1 Mac, correct? Are you using the pwnbox command line tool to run Pwnbox?

**Comment by HiddevH** [comment]
Correct, I have never ran X11 / GUI's from Docker before, so this issue was more my poor knowledge.

Searched some, followed the following procedure:
1. Install XQuartz
2. Open XQuartz, in the security tab, make sure Allow connections from network clients is enabled. Restart XQuartz.
3. In a terminal on the host, run `xhost + 127.0.0.1`
4. Pass `-e DISPLAY=host.docker.internal:0` into the Docker image
4.1 In my case: `docker run -d --name pwnbox --privileged --hostname pwnbox -p 2222:2222 -p 9000-9010:9000-9010 -v $HOME/.pwnbox/home:/root -v $HOME/.pwnbox/external:/mnt/external -e DISPLAY=host.docker.internal:0 deadpackets/pwnbox:v2.9.5`
5. Launch application from the Pwnbox CLI 

Perhaps useful to add this to a Wiki page for MacOS users @DeadPackets ?
