### ISSUE TITLE
Unable to nmap

### ISSUE THREAD

**Issue by HiddevH** [DeadPackets/pwnbox#6]
I have issues running nmap while in the Pwnbox, the error I get is displayed here:

```
Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-06 18:39 UTC
Initiating Ping Scan at 18:39
Scanning 123.123.123.123 [4 ports]
pcap_create(eth0) FAILED: eth0: SIOCETHTOOL(ETHTOOL_GET_TS_INFO) ioctl failed: Function not implemented.
Call to pcap_open_live() failed three times. There are several possible reasons for this, depending on your operating system:
LINUX: If you are getting Socket type not supported, try modprobe af_packet or recompile your kernel with PACKET enabled.
 *BSD:  If you are getting device not configured, you need to recompile your kernel with Berkeley Packet Filter support.  If you are getting No such file or directory, try creating the device (eg cd /dev; MAKEDEV <device>; or use mknod).
*WINDOWS:  Nmap only supports ethernet interfaces on Windows for most operations because Microsoft disabled raw sockets as of Windows XP SP2.  Depending on the reason for this error, it is possible that the --unprivileged command-line argument will help.
SOLARIS:  If you are trying to scan localhost or the address of an interface and are getting '/dev/lo0: No such file or directory' or 'lo0: No DLPI device found', complain to Sun.  I don't think Solaris can support advanced localhost scans.  You can probably use "-Pn -sT localhost" though.
```

I wonder if you encounter the same problem, or now a fix? I searched around a bit, but didn't find any hints on the web.

**Comment by DeadPackets** [comment]
Can you tell me more information about your host OS, your docker version
and pwnbox version?

**Comment by HiddevH** [comment]
Host OS: Apple M1 MacOS 11.6.1
Docker version: 20.10.11, build dea9396
Pwnbox version: v1.6.0 (tag pwnbox:latest on dockerhub)

**Comment by DeadPackets** [comment]
Hmmm, it might be an ARM issue. Fortunately enough I have an ARM server so
let me try building and running it there and I'll get back to you soon

**Comment by DeadPackets** [comment]
Can you also provide your Nmap command if possible?

**Comment by HiddevH** [comment]
Good pointer that it might be an ARM issue! 
I've rebuilt the docker container using 
`docker buildx build --platform linux/arm64 . -t pwnbox:arm64` 

After running this image with
`docker run --platform linux/arm64 -d --name pwnbox --privileged --hostname pwnbox -p 2222:2222 -p 9000-9010:9000-9010 -v $HOME/.pwnbox/home:/root -v $HOME/.pwnbox/external:/mnt/external pwnbox:arm64`
The nmap response:
```
nmap -v -sN 123.123.123.123
Starting Nmap 7.92 ( https://nmap.org ) at 2022-01-07 12:58 UTC
Initiating Ping Scan at 12:58
Scanning 123.123.123.123 [4 ports]
Completed Ping Scan at 12:58, 0.01s elapsed (1 total hosts)
Initiating Parallel DNS resolution of 1 host. at 12:58
Completed Parallel DNS resolution of 1 host. at 12:58, 0.94s elapsed
Initiating NULL Scan at 12:58
Scanning 123.123.123.123 [1000 ports]
```

This seems to be the solution. Can we add a --platform linux/arm64 build to the registry? :)

**Comment by DeadPackets** [comment]
I see, you must have been running the amd64 image then by accident.

I will add an arm64 build, just need to find a way to make it not take forever, because last time I tried the CI was stuck for more than an hour building everything.

I might add a feature to `pwnbox-cli` also to specify which platform image to use if it doesn't work after adding the build.
